### ISSUE TITLE
Chart Not Rendering with More Than 500 Entries

### ISSUE THREAD

**Issue by saulperez-hub** [montecristo7610/chart-gpt#1]
**Description**: When trying to create a chart with more than 1000 data points, the chart doesn't show up. The page appears to freeze and nothing is displayed. This happens with both line charts and bar charts.

**Steps to Reproduce**:
1. Open chart-gpt in your browser.
2. Upload a dataset with over 1000 entries.
3. Try to generate a line or bar chart with that data.

**Expected Behavior**: The chart should display normally, regardless of how many data points there are, even for large datasets.

**Actual Behavior**: The chart doesn't appear, and the page becomes unresponsive.

**Screenshots or Logs**: N/A

**Environment**:
- **Operating System**: Windows 11
- **Browser and Version**: Google Chrome 92
- **Node.js Version**: v14.17.3
- **Chart-gpt Version**: v1.0.5

**Additional Context**: This issue happens in both local development and live production environments. Lowering the number of data points below 1000 fixes the problem.

**Comment by EternalVision-AI** [comment]
Hello, @montecristo7610 
I've identified the problem.
I am working on the following enhancements:

**Pagination for large datasets**: This will limit the number of data points rendered per view, with the option to paginate through the entire dataset.
**Optimization of rendering**: We'll introduce performance improvements in the chart-rendering algorithm to handle large datasets more efficiently.
**Temporary Workaround**:
In the meantime, you can reduce the dataset size by pre-processing the data before rendering or consider using a sampling technique to plot fewer data points.
**Next Steps**:
 Implement pagination for datasets.
 Optimize the rendering algorithm.
 Test with large datasets (over 500 data points).
**ETA for the fix**: 1 week.

I'll keep this issue updated as we work on the fix. Thank you for your patience!
Please let us know if you encounter any additional issues!

**Comment by saulperez-hub** [comment]
Thanks for your suggestion.
I think it is the best solution.
Thanks again.
